version: 2.1

workflow: 
  version: 2
  build: 
    jobs: 
      - build: 
        filters: 
          branches: 
            only: 
              - main
jobs:
  build:
    working_directory: ~/CASimpleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
          name: install npm
          command: 'sudo npm install -g npm@5'
      - restore_cahe:
          key: dependency-cahe-{{ checksum "package-lock.json" }}
      - run: 
          name: install dependencies
          command: npm install
      - save_ cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: 
            - .node_modules